### ISSUE TITLE
Docker Compose raises Requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by SaintJackson** [ravirahman/neurips_blockflow1#1]
Hi, 

I encountered an HTTPConnection error when reproducing experiment 5.

I have successfully compiled the contract, and I have started ipfs and geth services via docker-compose. 

However, while I executed `python3 -m examples.logistic_regression.run_multi_clients --exp_name adult --dataset_folder ../results/adult/split_sym_eq_1_validation_fraction_0.2 --ground_truth_dataset ../results/adult/test.dat` from src file, it reports with the following error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74fe576470>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Is there any specific configuration I missed?

Look forward to your reply : )

**Comment by ravirahman** [comment]
Hi @SaintJackson ,

I believe the port is incorrect. Could you try 8545 instead of 8485? Sorry about the typo in the example config.

Best,
Ravi

**Comment by SaintJackson** [comment]
Hi @ravirahman ,

The port typo is a small deal, thanks for pointing it out. However, the bug I reproduce might be caused by other reasons.


I located the bug source might be inside the compose.yml file under /src/infra/local directory. 

`version: "3.7"
services:
  geth:
    build:
      context: "../geth"
    command: "${GETH_ARGS}"
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
  ipfs:
    image: "ipfs/go-ipfs:release"
    volumes: 
      - type: "volume"
        source: "ipfs_staging"
        target: "/export"
      - type: "volume"
        source: "ipfs_data"
        target: "/data/ipfs"
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002/udp"
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:5001:5001"
    expose:
      - "4001"
      - "4002"
      - "8080"
      - "5001"
volumes:
  ipfs_staging:
  ipfs_data:
`

From the .yml file, the ports 8545 and 8546 are automatically open when the geth image is freshly built up. Something weird now happened:

1. When I check docker images, an image called "local_geth: latest" is downloaded, which name I cannot find throughout the project code. I also check the name on dockerhub, it seems it's not there. What's interesting is, the image "local_geth:latest" has the same binaries as the docker image "ethereum/client/go:stable" does. Everything in Dockerfile was built inside "local_geth:latest" as well. 
2. When I execute a container by manually start from "local_geth:latest", it automatically assigned open ports 8545 and 8546 exposed. 
`CONTAINER ID   IMAGE        COMMAND   CREATED          STATUS        PORTS                                 NAMES
65b5819ea2b7   local_geth   "geth"    10 seconds ago   Up 1 second   8545-8546/tcp, 30303/tcp, 30303/udp   hardcore_hypatia`
However, when I execute the command line `python3 -m examples.logistic_regression.run_multi_clients --exp_name adult --dataset_folder ../results/adult/split_sym_eq_1_validation_fraction_0.2 --ground_truth_dataset ../results/adult/test.dat` from src, I encounter with the same problem as the last issue indicated.

So, should I manually start a container with specific ports from "local_geth:latest" image before I run python command? I am just confused about the logic, and I must have went through some steps incorrectly.

Look forward your reply : )

Sincerely,
Jackson

**Comment by SaintJackson** [comment]
Hi @ravirahman ,
 
The port typo is a small deal, thanks for pointing it out. However, the bug I reproduce might be caused by some reasons in terms of Dockerfile and docker-compose.yml file. Now I find two potential bugs:

1. Dockerfile's two [COPY] commands does not reference the correct directory of genesis.json and keyfile.json files ;
2. docker-compose.yml file does not build services from the current directory.

Best,
Jackson

**Comment by ravirahman** [comment]
Hi Jackson,

Can you double check that you are in the `src/infra/local` directory when running the docker commands? The following worked for me:

```
r_rahman@TIGER:~/neurips_blockflow1/src/infra/local$ docker-compose build
ipfs uses an image, skipping
Building geth
Sending build context to Docker daemon  18.94kB
Step 1/4 : FROM ethereum/client-go:v1.9.14
 ---> ccf55d6a0fc5
Step 2/4 : COPY genesis.json /var/run/genesis.json
 ---> Using cache
 ---> 43fafb2ce686
Step 3/4 : COPY keyfile.json /root/.ethereum/keystore/UTC--2020-05-27T04-41-22.275136264Z--79c6e305b86ac0ade141e59e9800ea115f730e74
 ---> Using cache
 ---> f3e1bba040e8
Step 4/4 : RUN geth init /var/run/genesis.json
 ---> Using cache
 ---> 55a8c9c6e182
Successfully built 55a8c9c6e182
Successfully tagged local_geth:latest
```

I also pushed https://github.com/ravirahman/neurips_blockflow1/commit/220ce953e1c1a469c7076e45785eab23a82bd896 to pin versions correctly, but I don't think this would affect the error that you are seeing.

Ravi

**Comment by SaintJackson** [comment]
Thanks Ravi, everything works fine now. Your commit to specify the version is really helpful!
